name: Build .NET MAUI Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install MAUI Workload
      run: dotnet workload install maui
    - name: Decrypt PFX-file
      run: |
        echo "${{ secrets.CERTIFICATE_PFX }}" > cert.pfx.asc
        certutil -decode cert.pfx.asc cert.pfx
    - name: Add Cert to Store
      run: certutil -user -q -p ${{ secrets.PASSWORD_PFX }} -importpfx cert.pfx NoRoot
    - name: Build
      run: dotnet publish src/uroskur.csproj -c Release -f:net6.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="${{ secrets.THUMBPRINT_PFX }}"
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        path: .\**\AppPackages\**\*.*
